### ISSUE TITLE
Error: invalid model and scorer

### ISSUE THREAD

**Issue by thejollypop** [johanneskropf/node-red-contrib-deepspeech-stt#2]
Hello @johanneskropf and thanks for this essential node!
I'm running on docker (Debian and Linux Alpine) and followed the `readme`, but getting the following error:

![image](https://user-images.githubusercontent.com/75426675/116604425-c7c77d80-a936-11eb-9c5e-6e0f50693ce6.png)

What am I doing wrong? Thanks

**Comment by johanneskropf** [comment]
You need to actually download the model and scorer to a folder on the machine that the node-red docker container is on and start the container with access to the location/folder that you downloaded the model and scorer too locally.
So something like `-v /path:/path/in/container` in your docker run command where path is the location that you downloaded the model and scorer file too on your machine and /path/in/container will be the path that you will have to use in the nodes config.

**Comment by thejollypop** [comment]
Thanks @johanneskropf , make sense.  If so, we can close this issue
